/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as authAuthImport } from './routes/(auth)/auth'
import { Route as AuthenticatedPracticeIndexImport } from './routes/_authenticated/practice/index'
import { Route as AuthenticatedPatientIndexImport } from './routes/_authenticated/patient/index'
import { Route as AuthenticatedPracticeScheduleImport } from './routes/_authenticated/practice/schedule'
import { Route as AuthenticatedPracticeExercisesImport } from './routes/_authenticated/practice/exercises'
import { Route as AuthenticatedPracticeDashboardImport } from './routes/_authenticated/practice/dashboard'
import { Route as AuthenticatedPracticePatientsIndexImport } from './routes/_authenticated/practice/patients/index'
import { Route as AuthenticatedPracticePatientsPatientIdImport } from './routes/_authenticated/practice/patients/$patientId'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authAuthRoute = authAuthImport.update({
  id: '/(auth)/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedPracticeIndexRoute = AuthenticatedPracticeIndexImport.update(
  {
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedPatientIndexRoute = AuthenticatedPatientIndexImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedPracticeScheduleRoute =
  AuthenticatedPracticeScheduleImport.update({
    id: '/practice/schedule',
    path: '/practice/schedule',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPracticeExercisesRoute =
  AuthenticatedPracticeExercisesImport.update({
    id: '/practice/exercises',
    path: '/practice/exercises',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPracticeDashboardRoute =
  AuthenticatedPracticeDashboardImport.update({
    id: '/practice/dashboard',
    path: '/practice/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPracticePatientsIndexRoute =
  AuthenticatedPracticePatientsIndexImport.update({
    id: '/practice/patients/',
    path: '/practice/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPracticePatientsPatientIdRoute =
  AuthenticatedPracticePatientsPatientIdImport.update({
    id: '/practice/patients/$patientId',
    path: '/practice/patients/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/auth': {
      id: '/(auth)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/practice/dashboard': {
      id: '/_authenticated/practice/dashboard'
      path: '/practice/dashboard'
      fullPath: '/practice/dashboard'
      preLoaderRoute: typeof AuthenticatedPracticeDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/practice/exercises': {
      id: '/_authenticated/practice/exercises'
      path: '/practice/exercises'
      fullPath: '/practice/exercises'
      preLoaderRoute: typeof AuthenticatedPracticeExercisesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/practice/schedule': {
      id: '/_authenticated/practice/schedule'
      path: '/practice/schedule'
      fullPath: '/practice/schedule'
      preLoaderRoute: typeof AuthenticatedPracticeScheduleImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/patient/': {
      id: '/_authenticated/patient/'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/practice/patients/$patientId': {
      id: '/_authenticated/practice/patients/$patientId'
      path: '/practice/patients/$patientId'
      fullPath: '/practice/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPracticePatientsPatientIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/practice/patients/': {
      id: '/_authenticated/practice/patients/'
      path: '/practice/patients'
      fullPath: '/practice/patients'
      preLoaderRoute: typeof AuthenticatedPracticePatientsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedPracticeDashboardRoute: typeof AuthenticatedPracticeDashboardRoute
  AuthenticatedPracticeExercisesRoute: typeof AuthenticatedPracticeExercisesRoute
  AuthenticatedPracticeScheduleRoute: typeof AuthenticatedPracticeScheduleRoute
  AuthenticatedPatientIndexRoute: typeof AuthenticatedPatientIndexRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
  AuthenticatedPracticePatientsPatientIdRoute: typeof AuthenticatedPracticePatientsPatientIdRoute
  AuthenticatedPracticePatientsIndexRoute: typeof AuthenticatedPracticePatientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPracticeDashboardRoute: AuthenticatedPracticeDashboardRoute,
  AuthenticatedPracticeExercisesRoute: AuthenticatedPracticeExercisesRoute,
  AuthenticatedPracticeScheduleRoute: AuthenticatedPracticeScheduleRoute,
  AuthenticatedPatientIndexRoute: AuthenticatedPatientIndexRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
  AuthenticatedPracticePatientsPatientIdRoute:
    AuthenticatedPracticePatientsPatientIdRoute,
  AuthenticatedPracticePatientsIndexRoute:
    AuthenticatedPracticePatientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth': typeof authAuthRoute
  '/practice/dashboard': typeof AuthenticatedPracticeDashboardRoute
  '/practice/exercises': typeof AuthenticatedPracticeExercisesRoute
  '/practice/schedule': typeof AuthenticatedPracticeScheduleRoute
  '/patient': typeof AuthenticatedPatientIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/practice/patients/$patientId': typeof AuthenticatedPracticePatientsPatientIdRoute
  '/practice/patients': typeof AuthenticatedPracticePatientsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth': typeof authAuthRoute
  '/practice/dashboard': typeof AuthenticatedPracticeDashboardRoute
  '/practice/exercises': typeof AuthenticatedPracticeExercisesRoute
  '/practice/schedule': typeof AuthenticatedPracticeScheduleRoute
  '/patient': typeof AuthenticatedPatientIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/practice/patients/$patientId': typeof AuthenticatedPracticePatientsPatientIdRoute
  '/practice/patients': typeof AuthenticatedPracticePatientsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/auth': typeof authAuthRoute
  '/_authenticated/practice/dashboard': typeof AuthenticatedPracticeDashboardRoute
  '/_authenticated/practice/exercises': typeof AuthenticatedPracticeExercisesRoute
  '/_authenticated/practice/schedule': typeof AuthenticatedPracticeScheduleRoute
  '/_authenticated/patient/': typeof AuthenticatedPatientIndexRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/_authenticated/practice/patients/$patientId': typeof AuthenticatedPracticePatientsPatientIdRoute
  '/_authenticated/practice/patients/': typeof AuthenticatedPracticePatientsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth'
    | '/practice/dashboard'
    | '/practice/exercises'
    | '/practice/schedule'
    | '/patient'
    | '/practice'
    | '/practice/patients/$patientId'
    | '/practice/patients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth'
    | '/practice/dashboard'
    | '/practice/exercises'
    | '/practice/schedule'
    | '/patient'
    | '/practice'
    | '/practice/patients/$patientId'
    | '/practice/patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/auth'
    | '/_authenticated/practice/dashboard'
    | '/_authenticated/practice/exercises'
    | '/_authenticated/practice/schedule'
    | '/_authenticated/patient/'
    | '/_authenticated/practice/'
    | '/_authenticated/practice/patients/$patientId'
    | '/_authenticated/practice/patients/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authAuthRoute: typeof authAuthRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authAuthRoute: authAuthRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/(auth)/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/practice/dashboard",
        "/_authenticated/practice/exercises",
        "/_authenticated/practice/schedule",
        "/_authenticated/patient/",
        "/_authenticated/practice/",
        "/_authenticated/practice/patients/$patientId",
        "/_authenticated/practice/patients/"
      ]
    },
    "/(auth)/auth": {
      "filePath": "(auth)/auth.tsx"
    },
    "/_authenticated/practice/dashboard": {
      "filePath": "_authenticated/practice/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/practice/exercises": {
      "filePath": "_authenticated/practice/exercises.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/practice/schedule": {
      "filePath": "_authenticated/practice/schedule.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/patient/": {
      "filePath": "_authenticated/patient/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/practice/": {
      "filePath": "_authenticated/practice/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/practice/patients/$patientId": {
      "filePath": "_authenticated/practice/patients/$patientId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/practice/patients/": {
      "filePath": "_authenticated/practice/patients/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
